### PR TITLE
Fix package set sorting

### LINKED ISSUE #328: sanity check in sort_package_sets_by_import_order fails in some cases
The following exception is triggered in some cases:
https://github.com/rock-core/autoproj/blob/700ae181206fbb6bb3560bf914e423582d8c8a11/lib/autoproj/ops/configuration.rb#L370

My theory is, root_pkg_set / "main configuration" is inserted just after the last explicit import, but there can be further imported dependencies if the last explicit package set has dependencies. Somehow the implicit dependencies seem to not being propagated properly to the root package set. A workaround is to add root pkg set also to the "target list" 

https://github.com/vbargsten/autoproj/commit/363008fab3c675f36664f62f4d3be7fe048fe8ca#diff-86d73a3e07d681adc4f4e2efba488f6709905a27818933f9a89b02cf2cbafbb2

### PR DESCRIPTION
**Pull request by 2maz**
Fixes #328 and corrects the load order of init.rb files to respect the import order of package sets

fyi @moooeeeep

### CODE REVIEW

File: lib/autoproj/ops/configuration.rb [hunk 1]
```diff
@@ -157,10 +157,10 @@ def create_remote_set_user_dir(vcs)
                 symlink_dest
             end
 
-            def load_package_set(vcs, options, imported_from)
+            def load_package_set(vcs, options, imported_from, initrb: true)
```
Comment (doudou) [inline lib/autoproj/ops/configuration.rb:160]: It seems that `load_package_set` is never used outside of `load_and_update_package_sets`. Now that you load init.rb within `update_package_sets`, the loading here should be removed.

File: lib/autoproj/ops/configuration.rb [hunk 2]
```diff
@@ -314,56 +314,56 @@ def inspect
...
-                    end
-                    if queue.size == last_size
-                        raise ArgumentError, "cannot resolve the dependencies between package sets. There seem to be a cycle amongst #{queue.map(&:name).sort.join(', ')}"
-                    end
+                name_to_pkg_set = Hash.new
+                pkg_sets = Hash.new
+                all_dependencies = []
+
+                package_sets.each do |p|
+                    name_to_pkg_set[p.name] = p
```
Comment (doudou) [inline lib/autoproj/ops/configuration.rb:326]: Is going through names really needed ? I would think that you should be using the package set object directly here (which would remove the need for `name_to_pkg_set`).

File: lib/autoproj/ops/configuration.rb [hunk 3]
```diff
@@ -314,56 +314,56 @@ def inspect
...
-                    dependencies = pkg_set.imports.dup
-                    if dependencies.empty?
-                        result.unshift(pkg_set)
-                    else
-                        i = result.find_index do |p|
-                            dependencies.delete(p)
-                            dependencies.empty?
+                unknown_pkg_sets = all_dependencies - pkg_sets.keys
+                unless unknown_pkg_sets.empty?
+                    raise "Unknown package sets found: #{unknown_pkg_sets}"
```
Comment (doudou) [inline lib/autoproj/ops/configuration.rb:337]: InternalError ?

File: lib/autoproj/ops/configuration.rb [hunk 4]
```diff
@@ -314,56 +314,56 @@ def inspect
...
+                end
+
+                sorted_pkg_sets = []
+                pending_pkg_sets = pkg_sets.keys
+
+                until pending_pkg_sets.empty?
+                    add = []
+                    progress = false
```
Comment (doudou) [inline lib/autoproj/ops/configuration.rb:345]: I believe that progress == true is the same as !add.empty? (i.e. no need for an extra flag)

File: lib/autoproj/ops/configuration.rb [hunk 5]
```diff
@@ -314,56 +314,56 @@ def inspect
...
+                    pending_pkg_sets.each do |pkg_set_name|
```
Comment (doudou) [inline lib/autoproj/ops/configuration.rb:346]: This is

~~~ ruby
add = pending_pkg_sets.find_all do |pkg_set_name|
   pkg_sets[pkg_set_name] -= sorted_pkg_sets
   pkg_sets[pkg_set_name].empty?
end
~~~

File: lib/autoproj/ops/configuration.rb [hunk 6]
```diff
@@ -314,57 +313,50 @@ def inspect
...
-                    end
-                    if queue.size == last_size
-                        raise ArgumentError, "cannot resolve the dependencies between package sets. There seem to be a cycle amongst #{queue.map(&:name).sort.join(', ')}"
-                    end
+                name_to_pkg_set = Hash.new
+                pkg_sets = Hash.new
+                all_pkgset_deps = Set.new
+
+                package_sets.each do |p|
+                    pkg_sets[p.name] = p.imports.to_a
```
Comment (doudou) [inline lib/autoproj/ops/configuration.rb:325]: My initial remark was related to `pkg_sets` too ... You could (I believe "should") use `p` as the key here.

Comment (doudou) [reply lib/autoproj/ops/configuration.rb:325]: Also, to avoid two loops, maybe `(package_sets.to_a + [root_pkg_set]).each` (arguable)

File: lib/autoproj/package_set.rb [hunk 7]
```diff
@@ -792,6 +832,24 @@ def resolve_overrides(key, vcs)
             vcs
         end
 
+        # Recursively resolve imports for a given package set
+        def self.resolve_imports(pkg_set, parents = Set.new)
+            return Set.new if pkg_set.imports.empty?
+
+            updated_parents = parents.dup
+            updated_parents << pkg_set
```
Comment (doudou) [inline lib/autoproj/package_set.rb:840]: updated_parents = parents | [pkg_set]

File: lib/autoproj/package_set.rb [hunk 8]
```diff
@@ -4,6 +4,45 @@ module Autoproj
...
     # dependencies that are provided by the operating system (.osdeps file).
     class PackageSet
+        # Comparator can be used to compare the list of package sets
+        # so that they can be sorted according to the following constraints:
+        # 1. dependencies among the package sets
+        # 2. order in which they are defined in the main configuration (manifest)
+        #
+        # Note that 1. naturally always takes precedence over 2. since 2.
+        # only affects a sorting of package sets that have no dependency
+        class Comparator
```
Comment (doudou) [inline lib/autoproj/package_set.rb:14]: This is really not an algorithm/property of the package sets, but of the overall configuration. Leave it in ops/configuration.rb

File: lib/autoproj/package_set.rb [hunk 9]
```diff
@@ -4,6 +4,45 @@ module Autoproj
...
+            def compare(pkgset_a, pkgset_b)
+                return 0 if pkgset_a == pkgset_b
+                return 1 if pkg_sets[pkgset_a].include?(pkgset_b)
+                return -1 if pkg_sets[pkgset_b].include?(pkgset_a)
+
+                # Check manifest precedence for pkgset_a != pkgset_b
+                return 0 unless main_imports.include?(pkgset_a)
+                return 0 unless main_imports.include?(pkgset_b)
+
+                if main_imports.index(pkgset_a) > main_imports.index(pkgset_b)
```
Comment (doudou) [inline lib/autoproj/package_set.rb:38]: main_imports.index(pkgset_a) <=> main_imports.index(pkgset_b)

File: lib/autoproj/package_set.rb [hunk 10]
```diff
@@ -4,6 +4,45 @@ module Autoproj
...
     class PackageSet
+        # Comparator can be used to compare the list of package sets
+        # so that they can be sorted according to the following constraints:
+        # 1. dependencies among the package sets
+        # 2. order in which they are defined in the main configuration (manifest)
+        #
+        # Note that 1. naturally always takes precedence over 2. since 2.
+        # only affects a sorting of package sets that have no dependency
+        class Comparator
+            attr_reader :pkg_sets, :main_imports
```
Comment (doudou) [inline lib/autoproj/package_set.rb:15]: Would you consider renaming `pkg_sets` into something like `imports_of` ? The name has really confused me.

File: lib/autoproj/package_set.rb (hunk 8 above)
Comment (doudou) [reply lib/autoproj/package_set.rb:14]: resolve_imports does make sense here though

File: lib/autoproj/ops/configuration.rb [hunk 11]
```diff
@@ -314,57 +313,20 @@ def inspect
...
-                        result.unshift(pkg_set)
-                    else
-                        i = result.find_index do |p|
-                            dependencies.delete(p)
-                            dependencies.empty?
-                        end
-                        result.insert(i + 1, pkg_set)
-                    end
+                c = PackageSet::Comparator.new(package_sets, root_pkg_set)
+                sorted_pkg_sets = c.pkg_sets.keys.sort do |a, b|
```
Comment (doudou) [inline lib/autoproj/ops/configuration.rb:321]: Better use `package_sets + [root_pkg_set]` here. Using `c.pkg_sets.keys` here feels like an anti-pattern to me. Or define a `all_package_sets` on Comparator and use that.

**Review by doudou — APPROVED** [review]

File: lib/autoproj/ops/configuration.rb [hunk 12]
```diff
@@ -1,9 +1,70 @@
...
+        # dependencies
+        class PackageSetHierarchy
+            attr_reader :imports_of, :dag
+
+            def initialize(package_sets, root_pkg_set)
+                @dag = RGL::DirectedAdjacencyGraph.new
+
+                @imports_of = Hash.new
+                package_sets.each do |p|
+                    dependencies = PackageSet.resolve_imports(p)
```
Comment (doudou) [inline lib/autoproj/ops/configuration.rb:23]: We don't need the recursive resolve_imports anymore, since the DAG does it naturally. Just iterate over all package sets and add edges for each direct dependency.

File: lib/autoproj/ops/configuration.rb [hunk 13]
```diff
@@ -1,9 +1,70 @@
...
+                    pkg_set = imports.shift
+                    imports.each do |p|
+                        if @imports_of[pkg_set].include?(p)
+                            raise "PackageSet '#{pkg_set.name}' depends on '#{p.name}', "\
+                                  "but is listed before it in the manifest"
+                        end
+                    end
+                end
+            end
+
```
Comment (doudou) [inline lib/autoproj/ops/configuration.rb:56]: The acyclic? test already takes care of what this was doing ... Maybe remove ? (which would get rid of @imports_of)

File: lib/autoproj/ops/configuration.rb (hunk 12 above)
Comment (2maz) [reply lib/autoproj/ops/configuration.rb:23]: It does only so if all the involved package sets are provided (or the tree depth is limited) and that does not seem to be guaranteed at that point?

Comment (doudou) [reply lib/autoproj/ops/configuration.rb:23]: It is guaranteed at this point. I've created a commit to document the whole class, but I think I'll propose it as a new PR after this one gets merged.

**Comment by doudou** [comment]
@2maz ... All good for me, feel free to merge
